name: 596-15_funprofiler
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - sourmash
  - pandas
  - bash_kernel=0.9.0
  - coreutils=9.1
  - r-irkernel=1.3.2
  - r-base=4.2.3
  - r-tidyverse=2.0.0
